version: '3'
services:
  twelvefa:
    build:
      context: .
    restart: always
    ports:
      - "3000:80"
  calcli:
    build:
      context: .
      dockerfile: ./cli/Dockerfile
    restart: always
    depends_on:
      - twelvefa
