version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.7

    working_directory: /home/circleci/twelvefa
    environment:
      ARTIFACTS: ./arfifacts
    steps:
      - checkout

      - run: ./install.ci.sh
      - run: mkdir $ARTIFACTS
      - run: go test -v . ./calc > $ARTIFACTS/tests.txt
      - run: cat $ARTIFACTS/tests.txt
      - run: go test ./calc -bench=. > $ARTIFACTS/benchmark.txt
      - run: cat $ARTIFACTS/benchmark.txt
      - run: go build
      - run: PORT=3000 ./twelvefa & # run the service in the background to test the client
      - run: go test -v ./cli >> $ARTIFACTS/cli-tests.txt
      - run: pkill ./twelvefa
      - run: cat $ARTIFACTS/cli-tests.txt

      - store_artifacts:
          path: $ARTIFACTS

  build:
    docker:
      - image: google/cloud-sdk:255.0.0

    working_directory: /home/circleci/twelvefa
    environment:
      IMAGE_NAME: twelvefa
    steps:
      - checkout

      - run:
          name: Install Docker # from a downloaded binary
          command: |
            set -x # better output formatting
            VER="19.03.1"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv -f /tmp/docker/* /usr/bin

      # Necessary step with CircleCI to use a newly installed Docker
      # https://circleci.com/docs/2.0/building-docker-images/#overview
      - setup_remote_docker

      - run: 
          name: Build the service Docker image
          command: >-
            docker build
            -t gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:latest
            --build-arg CIRCLECI_BUILD_NUMBER=${CIRCLE_BUILD_NUM} .
        
      - run: 
          name: Tag image with build nb
          command: >-
            docker tag
            gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:latest
            gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:${CIRCLE_BUILD_NUM}

      # TODO: login with gcloud

      # - run: 
      #     name: Push images
      #     command: |
      #       docker push gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:latest
      #       docker push gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:${CIRCLE_BUILD_NUM}


        ## TODO: deploy in another job

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - build:
          requires:
            - test