apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calcli
spec:
  replicas: 2
  strategy: {}
  template:
    spec:
      containers:
      - image: calcli
        name: calcli
      restartPolicy: Always
