apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twelvefa
spec:
  replicas: 3
  strategy: {}
  template:
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        image: twelvefa
        name: twelvefa
        ports:
        - containerPort: 80
      restartPolicy: Always
